version: '3.9'
services:
  database:
    build: ./images/database/

    environment:
      - HOSTNAME="database"

    volumes:
      - ./database_mount:/var/lib/database_mount/

    networks: 
      - service-network

    tty: true
    ports:
      - "5000:5000"

  mapping:
    build: ./images/mapping/

    environment:
      - HOSTNAME="mapping"

    volumes:
      - /home/bosqnux/Koodit/Oppari/data/testvideos:/home/bosqnux/Koodit/Oppari/data/testvideos 

    networks: 
      - service-network

    tty: true
    depends_on:
      - database

  labelling:
    build: ./images/labelling/

    environment:
      - HOSTNAME="labelling"

    networks: 
      - service-network

    volumes:
      - /home/bosqnux/Koodit/Oppari/data/testvideos:/home/bosqnux/Koodit/Oppari/data/testvideos 

    tty: true
    depends_on:
      - database

networks: 
  service-network:

